# Generated by Django 5.0 on 2023-12-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('products', models.ManyToManyField(to='website.product')),
            ],
        ),
    ]
