# Generated by Django 5.0 on 2023-12-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_bundles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bundles',
            new_name='Bundle',
        ),
    ]
