# Generated by Django 5.0 on 2023-12-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='products',
            field=models.ManyToManyField(related_name='bundles', to='website.product'),
        ),
    ]
