# Generated by Django 5.0 on 2024-01-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
