# Generated by Django 5.0 on 2024-01-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_blogpost_created_at_alter_blogpost_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-created_at',)},
        ),
    ]
