# Generated by Django 5.0 on 2024-01-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=10)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
