version: '3.3'
services:
    api:
        build: .
        image: crc.us:latest
        ports:
            - 5050:5000
        volumes:
            - type: bind
              source: .
              target: /app/

networks:
  default:
    name: nginx-proxy-manager_default